import type { Metadata } from 'next';
import './globals.css';
import PageTransitionEffect from '@/components/PageTransitions/PageTransitionEffect';
import localFont from 'next/font/local';
import BottomNavbar from '@/components/BottomNavbar';

export const saans = localFont({
    src: [
        {
            path: '../fonts/Saans-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../fonts/Saans-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../fonts/Saans-SemiBold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../fonts/Saans-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
    display: 'block',
    variable: '--font-saans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${saans.className} antialiased`}>
                <PageTransitionEffect>{children}</PageTransitionEffect>
                <BottomNavbar />
            </body>
        </html>
    );
}
