import type { Metadata } from "next";
import "./globals.css";;
import PageTransitionEffect from "@/components/PageTransitions/PageTransitionEffect";
import localFont from "next/font/local";

const saans = localFont({
  src: "../fonts/Saans-Regular.woff2",
  display: "auto"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saans.className} antialiased`}
      >
        <PageTransitionEffect>
          {children}
        </PageTransitionEffect>
      </body>
    </html>
  );
}
